#!/bin/bash

if [ "$#" -eq 1 ]; then
    date
    echo "rsync start"
    rsync -v "$1" xelalee@192.168.0.153:~/tftpboot/"$1"
    echo "rsync done"
elif [ -e "index.html" ]; then
    date
    echo "rsync index start"
    rsync -v index.html xelalee@192.168.0.153:~/tftpboot/index.html
    echo "rsync done"
else 
    read -p "file to scp? " fl
    if [ -e "$fl" ]; then
        date
        echo "rsync start"
        rsync -v "$fl" xelalee@192.168.0.153:~/tftpboot/"$fl"
        echo "rsync done"
    fi
fi
