#!/bin/bash 

if [ "$#" -eq 1 ]; then
    date               
    echo "tftp get $1" 
    tftp -g -r $1 10.10.1.2
    echo "tftp get done"      
elif [ -e "index.html" ]; then
    date                      
    echo "tftp get index.html"
    tftp -g -r index.html 10.10.1.2
    echo "tftp get done"                
fi 
