DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT
(
  ACCOUNT_ID         INTEGER                     NOT NULL,
  USERNAME           VARCHAR(32),
  PASSWORD           VARCHAR(128),
  PASSWORD_HINT      VARCHAR(80),
  FIRST_NAME         VARCHAR(32),
  LAST_NAME          VARCHAR(32),
  COMPANY            VARCHAR(128),
  ADDRESS            VARCHAR(128),
  CITY               VARCHAR(40),
  STATE              VARCHAR(40),
  COUNTRY_CODE       VARCHAR(4),
  POSTAL_CODE        VARCHAR(10),
  PHONE              VARCHAR(20),
  FAX                VARCHAR(20),
  EMAIL              VARCHAR(50),
  TIME_ZONE_CODE     VARCHAR(2),
  LOGIN_COUNT        INTEGER,
  LAST_VIEWED_IP     VARCHAR(20),
  STATUS             VARCHAR(20),
  LAST_VIEWED_DATE   DATETIME,
  CREATE_DATE        DATETIME,
  CREATE_BY          VARCHAR(50),
  UPDATE_DATE        DATETIME,
  UPDATE_BY          VARCHAR(50),
  LOGIN_STATUS       VARCHAR(1),
  REMINDER           VARCHAR(10)          DEFAULT 'T',
  REMINDER_LANG      VARCHAR(10)          DEFAULT 'en',
  SUBSCRIPTION_CODE  VARCHAR(64),
  PRIMARY KEY  (ACCOUNT_ID),
  UNIQUE(USERNAME)
)CHARSET=utf8;

DROP TABLE IF EXISTS LICENSE;
CREATE TABLE LICENSE
(
  LICENSE_KEY      VARCHAR(128)           NOT NULL,
  SN               VARCHAR(32),
  BEGIN_DATE       DATETIME,
  SUSPEND_COUNT    INTEGER,
  STATUS           VARCHAR(20),
  SERVICE_ID       INTEGER,
  SERVICE_TYPE_ID  VARCHAR(1),
  SERVICE_CODE     VARCHAR(10),
  CARD_TYPE        VARCHAR(20),
  MY_SERVICE_ID    INTEGER,
  ORDER_ID         VARCHAR(40),
  UPDATE_DATE      DATETIME,
  CREATE_DATE      DATETIME,
  PRIMARY KEY  (LICENSE_KEY),
  UNIQUE(SN)
)CHARSET=utf8;

DROP TABLE IF EXISTS MODEL;
CREATE TABLE MODEL
(
  MODEL_ID      INTEGER                          NOT NULL,
  MODEL_NAME    VARCHAR(80),
  CARD_TYPE     VARCHAR(80)
)CHARSET=utf8;

DROP TABLE IF EXISTS MODEL2SERVICE;
CREATE TABLE MODEL2SERVICE
(
  MODEL_ID         INTEGER                       NOT NULL,
  SERVICE_TYPE_ID  VARCHAR(1)                    NOT NULL,
  SERVICE_CODE     VARCHAR(10)                   NOT NULL,
  SERVICE_ID       INTEGER                       NOT NULL
)CHARSET=utf8;

DROP TABLE IF EXISTS MY_PRODUCT;
CREATE TABLE MY_PRODUCT
(
  MY_PRODUCT_ID        INTEGER                   NOT NULL,
  ACCOUNT_ID           INTEGER                   NOT NULL,
  MODEL_ID             INTEGER                   NOT NULL,
  SN                   VARCHAR(40)        NOT NULL,
  MAC                  VARCHAR(40),
  FRIENDLY_NAME        VARCHAR(80),
  STATUS               VARCHAR(20),
  CREATE_DATE          DATETIME,
  CREATE_BY            VARCHAR(50),
  UPDATE_DATE          DATETIME,
  UPDATE_BY            VARCHAR(50),
  FLAG                 VARCHAR(1),
  PURCHASE_DATE        DATETIME,
  PURCHASE_FROM        VARCHAR(30),
  COUNT                INTEGER,
  PRIMARY KEY (MY_PRODUCT_ID)
)CHARSET=utf8;

DROP TABLE IF EXISTS MY_SERVICE;
CREATE TABLE MY_SERVICE
(
  MY_SERVICE_ID    INTEGER                       NOT NULL,
  MY_PRODUCT_ID    INTEGER                       NOT NULL,
  SERVICE_ID  INTEGER                       NOT NULL,
  SERVICE_TYPE_ID  VARCHAR(1)             NOT NULL,
  SERVICE_CODE     VARCHAR(10)            NOT NULL,
  SUSPEND_DATE     DATETIME,
  SUSPEND_COUNT    INTEGER,
  STATUS           VARCHAR(20),
  REMARK           VARCHAR(128),
  BEGIN_DATE       DATETIME,
  EXPIRATION_DATE  DATETIME,
  REACTIVATE_DATE  DATETIME,
  VALUE            INTEGER                   DEFAULT 0,
  ORIGINAL_DATE    DATE,
  UPDATE_DATE      DATETIME,
  PRIMARY KEY (MY_SERVICE_ID)
)CHARSET=utf8;

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT
(
  SN        VARCHAR(80)        NOT NULL,
  MAC       VARCHAR(20),
  MODEL_ID             INTEGER                   NOT NULL,
  CREATE_DATE          DATETIME,
  UNIQUE(SN),
  UNIQUE(MAC)
)CHARSET=utf8;

DROP TABLE IF EXISTS COUNTRY_CODE;
CREATE TABLE COUNTRY_CODE
(
  CODE         VARCHAR(64),
  DESCRIPTION  VARCHAR(128),
  VALUE1       VARCHAR(64),
  VALUE2       VARCHAR(64),
  VALUE3       VARCHAR(64),
  VALUE4       VARCHAR(64),
  VALUE5       VARCHAR(64)
)CHARSET=utf8;

DROP TABLE IF EXISTS SEQUENCE_ID;
CREATE TABLE SEQUENCE_ID
(
  NAME    VARCHAR(130),
  NEXTID  INTEGER,
  UNIQUE(NAME)
)CHARSET=utf8;

DROP TABLE IF EXISTS SERVICE;
CREATE TABLE SERVICE
(
  SERVICE_ID          INTEGER                    NOT NULL,
  SERVICE_NAME        VARCHAR(64),
  SERVICE_SHORT_NAME  VARCHAR(10),
  TRIAL2STD_EXTRA     INTEGER,
  PRIMARY KEY (SERVICE_ID)
)CHARSET=utf8;

DROP TABLE IF EXISTS SKU;
CREATE TABLE SKU
(
  SERVICE_TYPE_ID  VARCHAR(1)             NOT NULL,
  SERVICE_CODE     VARCHAR(10)            NOT NULL,
  ATTRIBUTE        VARCHAR(20)            NOT NULL,
  ATTRIBUTE_TYPE   VARCHAR(64)             NOT NULL,
  VALUE            VARCHAR(20)            NOT NULL
)CHARSET=utf8;

DROP TABLE IF EXISTS SN_SEQ;
CREATE TABLE SN_SEQ
(
  MONTH    VARCHAR(4),
  TYPE     VARCHAR(4),
  SEQ      INTEGER,
  UNIQUE(MONTH, TYPE)
)CHARSET=utf8;

DROP TABLE IF EXISTS ADMINISTRATOR;
CREATE TABLE ADMINISTRATOR
(
  ACCOUNT_ID         INTEGER                     NOT NULL,
  USERNAME           VARCHAR(32),
  PASSWORD           VARCHAR(128),
  EMAIL              VARCHAR(50),
  GROUP_ID           INTEGER                          NOT NULL,
  PRIMARY KEY  (ACCOUNT_ID),
  UNIQUE(USERNAME)
)CHARSET=utf8;

DROP TABLE IF EXISTS FUNCTION;
CREATE TABLE FUNCTION
(
  FUNCTION_ID    INTEGER                         NOT NULL,
  MENU_ID        INTEGER                         NOT NULL,
  FUNCTION_NAME  VARCHAR(64),
  URL            VARCHAR(256),
  SORT_ID        VARCHAR(4),
  UNIQUE(FUNCTION_ID)
)CHARSET=utf8;

DROP TABLE IF EXISTS FUNCTION2GROUP_NAME;
CREATE TABLE FUNCTION2GROUP_NAME
(
  FUNCTION_ID   INTEGER                          NOT NULL,
  GROUP_ID      INTEGER                          NOT NULL
)CHARSET=utf8;

DROP TABLE IF EXISTS GROUP_NAME;
CREATE TABLE GROUP_NAME
(
  GROUP_ID      INTEGER                          NOT NULL,
  GROUP_NAME    VARCHAR(64)
)CHARSET=utf8;

DROP TABLE IF EXISTS MENU;
CREATE TABLE MENU
(
  MENU_ID    INTEGER                             NOT NULL,
  MENU_NAME  VARCHAR(64),
  URL        VARCHAR(256),
  SORT_ID    VARCHAR(4)
)CHARSET=utf8;


