CREATE OR REPLACE VIEW GET_SKU_VIEW
(MY_PRODUCT_ID, MAC, MY_SERVICE_ID, SERVICE_ID, 
 SERVICE_CODE, BEGIN_DATE, EXPIRATION_DATE, REACTIVATE_DATE, SERVICE_TYPE_ID, 
 STATUS, SKU_ATTRIBUTE,SKU_ATTRIBUTE_TYPE, SKU_VALUE)
AS 
SELECT mp.MY_PRODUCT_ID,
mp.MAC,
ms.MY_SERVICE_ID,
ms.SERVICE_ID,
ms.SERVICE_CODE,
ms.BEGIN_DATE,
ms.EXPIRATION_DATE,
ms.REACTIVATE_DATE,
ms.SERVICE_TYPE_ID,
ms.STATUS,
SKU.ATTRIBUTE SKU_ATTRIBUTE,
SKU.ATTRIBUTE_TYPE SKU_ATTRIBUTE_TYPE,
(CASE
WHEN SKU.ATTRIBUTE_TYPE='date' THEN to_days(ms.EXPIRATION_DATE)-to_days(now())
WHEN SKU.ATTRIBUTE_TYPE='number' AND ms.SERVICE_TYPE_ID='S' THEN ms.VALUE
WHEN SKU.ATTRIBUTE_TYPE='number' AND ms.SERVICE_TYPE_ID='T' THEN SKU.VALUE
WHEN SKU.ATTRIBUTE_TYPE='boolean' THEN SKU.VALUE
END) SKU_VALUE
FROM MY_PRODUCT mp, MY_SERVICE ms, SKU
WHERE mp.MY_PRODUCT_ID=ms.MY_PRODUCT_ID
AND ms.SERVICE_CODE=SKU.SERVICE_CODE 
and ms.SERVICE_TYPE_ID=SKU.SERVICE_TYPE_ID;

CREATE OR REPLACE VIEW PRODUCT_SERVICE_LICENSE_VIEW
(MY_PRODUCT_ID,ACCOUNT_ID,MODEL_ID,MODEL_NAME,SN,MAC,
MY_SERVICE_ID,SERVICE_ID,SERVICE_NAME,SERVICE_TYPE_ID,SERVICE_CODE,
STATUS,REMARK,BEGIN_DATE,EXPIRATION_DATE,VALUE,LICENSE_KEY,CARD_TYPE)
AS 
SELECT mp.MY_PRODUCT_ID,
mp.ACCOUNT_ID,
mp.MODEL_ID,
m.MODEL_NAME,
mp.SN,
mp.MAC,
ms.MY_SERVICE_ID,
ms.SERVICE_ID,
s.SERVICE_NAME,
ms.SERVICE_TYPE_ID,
ms.SERVICE_CODE,
ms.STATUS,
ms.REMARK,
ms.BEGIN_DATE,
ms.EXPIRATION_DATE,
ms.VALUE,
lk.LICENSE_KEY,
lk.CARD_TYPE
FROM MY_PRODUCT mp, MODEL m, MY_SERVICE ms,SERVICE s, LICENSE lk
WHERE mp.MODEL_ID=m.MODEL_ID 
AND mp.MY_PRODUCT_ID=ms.MY_PRODUCT_ID
AND ms.SERVICE_ID=s.SERVICE_ID
AND ms.MY_SERVICE_ID=lk.MY_SERVICE_ID;
     

           